#.travis.yml

language: node_js
node_js:
  - "7.8"

branches:
  only:
    - development

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod

after_success:


notifications:
  email:
    on_failure: change
    on_success: change