#.travis.yml

language: node_js

node_js:
  - "7.8"

branches:
  only:
    - development

script: node_modules/karma/bin/karma start test/karma.conf.js --single-run

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

notifications:
  email:
    on_failure: change
    on_success: change