#.travis.yml
sudo: required
dist: trusty
language: node_js

node_js:
  - "7"

branches:
  only:
    - development

#script: node --max_old_space_size=2048 ./node_modules/karma/bin/karma start ./karma.conf.js --single-run

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g @angular/cli
  - npm install -g karma
  - npm install


notifications:
  email:
    on_failure: change
    on_success: change