#.travis.yml

language: node_js

node_js:
  - "7.8"

branches:
  only:
    - development

#addons:
#apt:
#  sources:
#    - google-chrome
#  packages:
#    - google-chrome-stable
#    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

notifications:
  email:
    on_failure: change
    on_success: change